Vagrant.configure("2") do |config|
  config.vm.box = 'digital_ocean'
  config.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
  config.ssh.private_key_path = '~/.ssh/id_rsa'
  config.vm.synced_folder ".", "/vagrant", disabled: true
  #
  config.vm.define "HackerNewsWebApp", primary: true do |server|

    server.vm.provider :digital_ocean do |provider|
      provider.ssh_key_name = "Vagrant"
      provider.token = '7c0c7cc33a161798d6f8ae829609c826c8237206a7b19ae7282da8e1cc609248'
      provider.image = 'ubuntu-16-04-x64'
      provider.region = 'fra1'
      provider.size = '512mb'
      provider.privatenetworking = true
    end

    server.vm.hostname = "HackerNewsWebApp"
    server.vm.provision "shell", inline: <<-SHELL
		
		sudo apt-get update
		sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
		echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" | sudo tee /etc/apt/sources.list.d/docker.list
		sudo apt-get update
		apt-cache policy docker-engine
		sudo apt-get install -y docker-engine
		
		sudo chmod 700 ~/.ssh
		
		sudo echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDoqHjzR547kAzN2HsRxwuiipeLpAbyM9ZN8JMDg0DzzxsExqKZJC2txil//kKqsYRLEbK3ZoqXIaIYRkYmMYoFt7CQk34ZFY0WEA66lu+sKCFfCtk0pweRJCxkNY5nqb6aI/R7ON6aqtAtXlbTp4HGwwllVsuA7Ap4x5EMjo+RuIUdkhsKo6rTl+ty55i86mMTdxdY5pOsCZDLDqEV6zkyRfkYU7pxnfJLL0zFreEFtbH3JAN9d++RuVoKK5HKPlHpn0VjdmMs8xCrS45GmIQybC8P0t+//jLk9JBd48jWUL269JuthOUDZKaZD+XdULrvoIg4fLkPr74miKxfOA9TiSKMDTiInt9mnYVV26ce+JKg7tWFZ3Gnb+6WUBdwkS2IhGmw/NcpaMuSq2Ru7JXHJGO9EcQhjTg5ALX45Cv++mYzOZgis5EYzaZHBVw+sOphq2K7DosKc1Cv0XK1dvT1cfs2/0EQ+hb7IerP5NNV3Y+lrDPdo1AK+LPd3wX73ZCNhs3crJOJcApzPKlaOdGhG3Y+20wOGRAZYG8k4MPiCnW2vomhrgLY7fXjd1l+Pf4G+MLw2yHUPu3ILRFNaCGc83UJdP+TamkFU7yKisZXmjrNK2Is7GJxtpRJtEHKg6YZc/MJ6UwfNST3pW8SRxUTh5PEQlcTrj6XYRKc90RK2w== Animcuil@gmail.com\n">> ~/.ssh/authorized_keys
		sudo cat "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDSKf3TBR0jDrqGQNMeZVJGs/oOTnO7ILVX3T56kumpmYxIzaMFrGENx/cxKcY2sE599LMvYPI2oYidqoGq/NJg2X0IdnC5B3XMJcx0vSPtrDYYGzwWcG6uEvdqG8+jjFR+oXGspGc8ys3sUTJe9sGEVIUPNuwZvsXiFpHgVIbnZNmW+yrzS4+3ZUu/KZSEaqc/T5FvJbEdjUtjeGNWy5vbokCsj/HGjvTAJVgLYh6bgzStjljIlmhMNa1k23sxIpD/QImvOZeNq2oXySWW3wCxTDfMZlaMvZPFD2EvuFuD6rku9qUuL/+12WdYZViDufXE+WOKqQHMe/XA1vY8A9rVI+7BAlxcAo9O49xnFAScY69d41k0DQwXotX73RM1Q70Mq/Wdz0d0aKePhiQmuGSCUaG6miPkF2kfTpYrp9Iqg6VYpEgw1SpOjAAx+M1vXnGSkpjRLPe2nu+fR4ouipXQFQHFDSpRUfZOKP+7fQOWB25iyciYWssekdAJfnlJ176kPN6zFMdqVp5bgxP4taloHQV4evrenzNFrz2iq/oZkrmkLMVG+300IBA8T1DPAoBuUtRlMde9D9xqOCoCdz8MqsjpbwWmT0P+uGbTR0SFBWiC2dylXqXATUsCZBjYOBjhAmtVCGYYtW9/BobfnGcjhKHOGY6jZP6TDI6TCFBVdQ== Animcuil@gmail.com\n">> ~/.ssh/authorized_keys
		sudo echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDhUDRVQzTiuWSyU+zMsYq+KHdGMgtP59vTEUarGT6rJ1o54oyAadFxiKs5fIqQ/YPDwQxtXI14vVvE7OF6EewIaZBVAH1wbU3BuGbpqpkUbo6RZeB33WfIGftG7zr2kIpq4BrKkfuTTzp/MIQoW2CH2/4pki4T+bniPjPBbcKCAEsImVp767wBeaRrOCX2dhCIrcHgHrH+/9ruetkjc5mllKi7W5NkYDDSvHTce7whI4xtYVOGzGflXnv6K3gY51LZ7PmNA27Z1mPU5hDDcFfQ9DRi+ids3YlScoavDr+sQr+KjzET1TpLl7zF6nN7GkT0+//gD4RUjfMAdH6Jayf1 jenkins@JenkinsServer\n">> ~/.ssh/authorized_keys
		sudo echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqXvjIYrfp6jnh5/L+WL0kNSrGQ7Nn3mi/72Lco0mqby/tj1rkfG3nonfDf/7v2iiCIV5ggXxWBJoc4qo3Rrgrn3/Q/joQi/UBPJPvXsUtsqpd54cXhRdP+GTKzPGqzHnjpfvYi5xUFJdN5LtPBKYrDKN5dgipUFpX741lFWEiXVP7rYtCpo+ZFFB15AZ8WzctYRMiGrPyckM4kM0nRmlZUlBzszZqJsaJaqSQi6bypiBvPJ/5RoqXCkeecJAVjST0RaegX3iuZfOeaFEIk7gOh3Y/dbqfXc1ttr5+igkJjviD1n1aCQ52mI+gbLJ49cWP5tASikelJqR3/mpjYdjn Emmely@Lenovo-PC\n">> ~/.ssh/authorized_keys
		sudo echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/ap5l5R1kNFcVFw7fjREW+S08W1Bb7H4QeWSpOXMm4AKqh1Gtoj6ROwcvBBRZxzEwKNsYwZ9W8AxFtwVDyDJdGWL1zjaBp6Y1iNYe09EjWZdITCT5ETDKjpuKs7iYy6W9bWWwoEWhe06jAXjS/r/TomZn6kcfkkeh/P6mNTWf2tGHJceUJb7tqj/k0o8TafI+LLA9PVWnbgZQGTteEvbxQVsDjlGMMzAQaTMzlKHLJHbqDTBssflEuoRJQZRqeyQt/dH1P63o0xhBluUucpGAUg/H9YjFpn9FahZCAUAIxtmd9gA17TQxfS43hAP+0X42fAIZnSQ9swtxsZRiJpNZ reape@LAPTOP-RNIGIGP9\n">> ~/.ssh/authorized_keys
		
		sudo chmod 600 ~/.ssh/authorized_keys
		wget https://raw.githubusercontent.com/DanielHauge/HackerNews-Grp8/master/ProjectFolders/WebApplication/deploy2.sh
		chmod u+x ./deploy2.sh
		
		
		
    SHELL
  end


end
